name: Argos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  argos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Upload screenshots to argos-ci.com
        continue-on-error: true
        run: npm exec @argos-ci/cli upload ./screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
